maintenance: refactor

diff --git a/maintenance b/maintenance
--- a/maintenance
+++ b/maintenance
@@ -1,86 +1,86 @@
 #!/bin/sh
 
 if [ "$(whoami)" != "root" ]; then
-    if [ -n "$(which sudo)" ]; then
-		echo "\$ sudo $0 $*"
-		sudo $0 $@
-	else
-		echo "\$ su -c "$0 $*" root"
-		su -c "$0 $*" root
-	fi
-    exit $?
+  if [ -n "$(which sudo)" ]; then
+    echo "\$ sudo $0 $*"
+    sudo "$0" "$@"
+  else
+    echo "\$ su -c \"$0 $*\" root"
+    su -c "$0 $*" root
+  fi
+  exit $?
 fi
 
 if [ -t 1 ] && [ "$(tput colors)" -ge 16 ] 2>/dev/null; then
-    RED="$(tput setaf 9)"
-    GREEN="$(tput setaf 10)"
-    YELLOW="$(tput setaf 11)"
-    BLUE="$(tput setaf 12)"
-    MAGENTA="$(tput setaf 13)"
-    CYAN="$(tput setaf 14)"
-    RESET="$(tput sgr0)"
+  RED="$(tput setaf 9)"
+  GREEN="$(tput setaf 10)"
+  YELLOW="$(tput setaf 11)"
+  BLUE="$(tput setaf 12)"
+  MAGENTA="$(tput setaf 13)"
+  CYAN="$(tput setaf 14)"
+  RESET="$(tput sgr0)"
 fi
 
 showProgress() {
-	echo "${CYAN}>>> $1...${RESET}"
+  echo "${CYAN}>>> $1...${RESET}"
 }
 
 tryRun() {
-	$*
-	retcode=$?
-	if [ "$retcode" -ne "0" ]; then
-		echo "${RED}Failed! code: $retcode${RESET}"
-		exit 1
-	fi
+  $*
+  retcode=$?
+  if [ "$retcode" -ne "0" ]; then
+    echo "${RED}Failed! code: $retcode${RESET}"
+    exit 1
+  fi
 }
 
 dryRunApt() {
-	showProgress "Update catalog"
-        tryRun apt-get update
-        showProgress "List upgradable"
-        tryRun apt list --upgradable
+  showProgress "Update catalog"
+  tryRun apt-get update
+  showProgress "List upgradable"
+  tryRun apt list --upgradable
 }
 
 maintenanceApt() {
-	showProgress "Update catalog"
-	tryRun apt-get update
-	showProgress "Fix missing"
-	tryRun apt-get install -f -y
-	showProgress "Upgrade package"
-	tryRun apt-get dist-upgrade -y
-	showProgress "Remove redudant"
-	tryRun apt-get autoremove -y
-	showProgress "Clean archive"
-	tryRun apt-get autoclean
-	showProgress "Purge configuration"
-	dpkg -l | grep ^rc | awk '{print $2}' |
-		while read packagename; do
-			tryRun dpkg --purge "$packagename"
-		done
+  showProgress "Update catalog"
+  tryRun apt-get update
+  showProgress "Fix missing"
+  tryRun apt-get install -f -y
+  showProgress "Upgrade package"
+  tryRun apt-get dist-upgrade -y
+  showProgress "Remove redudant"
+  tryRun apt-get autoremove -y
+  showProgress "Clean archive"
+  tryRun apt-get autoclean
+  showProgress "Purge configuration"
+  dpkg -l | grep ^rc | awk '{print $2}' |
+    while read packagename; do
+      tryRun dpkg --purge "$packagename"
+    done
 }
 
 maintenanceSnap() {
-	showProgress "Refresh snaps"
-	snap refresh
+  showProgress "Refresh snaps"
+  snap refresh
 
-	showProgress "Remove disabled snaps"
-	snap list --all | awk '/disabled/{print $1, $3}' |
-		while read snapname revision; do
-			tryRun snap remove "$snapname" --revision="$revision"
-		done
+  showProgress "Remove disabled snaps"
+  snap list --all | awk '/disabled/{print $1, $3}' |
+    while read snapname revision; do
+      tryRun snap remove "$snapname" --revision="$revision"
+    done
 }
 
 if [ "$1" = "-d" ] || [ "$1" = "--dry-run" ]; then
-	dryRunApt
-	exit 0
+  dryRunApt
+  exit 0
 fi
 
-if [ -n "$(which apt-get)" ]; then
-	maintenanceApt
+if which apt-get >/dev/null; then
+  maintenanceApt
 else
-	echo "${YELLOW}apt-get command not found${RESET}"
+  echo "${YELLOW}apt-get command not found${RESET}"
 fi
 
-if [ -n "$(which snap)" ]; then
-	maintenanceSnap
+if which snap >/dev/null && pgrep snapd >/dev/null; then
+  maintenanceSnap
 fi
